// Icons from:
// https://cdn.jsdelivr.net/gh/mp3towav9184/Currency-Icons/<CURRENCY CODE>.svg

export default {
	vuv: 'Ni-Vanuatu Vatu',
	btg: 'Bitcoin Gold',
	link: 'Chainlink',
	sgd: 'Singapore Dollar',
	qnt: 'Quant',
	mtl: 'Maltese Lira',
	jmd: 'Jamaican Dollar',
	'1inch': '1inch',
	ksm: 'Kusama',
	ron: 'Romanian Leu',
	jod: 'Jordanian Dinar',
	tmt: 'Turkmenistani Manat',
	khr: 'Cambodian Riel',
	btc: 'Bitcoin',
	pkr: 'Pakistani Rupee',
	ht: 'Huobi Token',
	bif: 'Burundian Franc',
	dop: 'Dominican Peso',
	czk: 'Czech Koruna',
	pgk: 'Papua New Guinean Kina',
	lsl: 'Basotho Loti',
	kpw: 'North Korean Won',
	myr: 'Malaysian Ringgit',
	npr: 'Nepalese Rupee',
	lbp: 'Lebanese Pound',
	etb: 'Ethiopian Birr',
	sll: 'Sierra Leonean Leone',
	ghs: 'Ghanaian Cedi',
	dkk: 'Danish Krone',
	rub: 'Russian Ruble',
	ils: 'Israeli Shekel',
	gtq: 'Guatemalan Quetzal',
	thb: 'Thai Baht',
	byn: 'Belarusian Ruble',
	omr: 'Omani Rial',
	dash: 'Digital Cash',
	doge: 'Dogecoin',
	comp: 'Compound',
	xaf: 'Central African CFA Franc BEAC',
	uah: 'Ukrainian Hryvnia',
	bat: 'Basic Attention Token',
	gusd: 'Gemini US Dollar',
	dcr: 'Decred',
	try: 'Turkish Lira',
	sol: 'Solana',
	cuc: 'Cuban Convertible Peso',
	mwk: 'Malawian Kwacha',
	snx: 'Synthetix Network',
	kmf: 'Comorian Franc',
	xlm: 'Stellar Lumen',
	kgs: 'Kyrgyzstani Som',
	vet: 'Vechain',
	eos: 'EOS',
	fil: 'Filecoin',
	djf: 'Djiboutian Franc',
	crv: 'Curve DAO Token',
	bgn: 'Bulgarian Lev',
	chf: 'Swiss Franc',
	mur: 'Mauritian Rupee',
	kes: 'Kenyan Shilling',
	sar: 'Saudi Arabian Riyal',
	neo: 'NEO',
	aave: 'Aave',
	mxn: 'Mexican Peso',
	hnl: 'Honduran Lempira',
	krw: 'South Korean Won',
	algo: 'Algorand',
	ttd: 'Trinidadian Dollar',
	mop: 'Macau Pataca',
	all: 'Albanian Lek',
	sand: 'The Sandbox',
	sek: 'Swedish Krona',
	mkr: 'Maker',
	iqd: 'Iraqi Dinar',
	top: "Tongan Pa'anga",
	uzs: 'Uzbekistani Som',
	srd: 'Surinamese Dollar',
	azn: 'Azerbaijan Manat',
	amd: 'Armenian Dram',
	nlg: 'Dutch Guilder',
	afn: 'Afghan Afghani',
	ape: 'ApeCoin',
	mkd: 'Macedonian Denar',
	nio: 'Nicaraguan Cordoba',
	dai: 'DAI',
	eur: 'Euro',
	clp: 'Chilean Peso',
	usdt: 'Tether',
	mad: 'Moroccan Dirham',
	kwd: 'Kuwaiti Dinar',
	fjd: 'Fijian Dollar',
	gno: 'Gnosis',
	stx: 'Stacks',
	bam: 'Bosnian Convertible Mark',
	ar: 'Arweave',
	ern: 'Eritrean Nakfa',
	brl: 'Brazilian Real',
	enj: 'Enjin Coin',
	lkr: 'Sri Lankan Rupee',
	szl: 'Swazi Lilangeni',
	usd: 'US Dollar',
	lak: 'Lao Kip',
	kzt: 'Kazakhstani Tenge',
	ves: 'Venezuelan Bol\u00edvar',
	hkd: 'Hong Kong Dollar',
	pyg: 'Paraguayan Guarani',
	mnt: 'Mongolian Tughrik',
	cop: 'Colombian Peso',
	shp: 'Saint Helenian Pound',
	gnf: 'Guinean Franc',
	mru: 'Mauritanian Ouguiya',
	icp: 'Internet Computer',
	gel: 'Georgian Lari',
	lyd: 'Libyan Dinar',
	idr: 'Indonesian Rupiah',
	yer: 'Yemeni Rial',
	kyd: 'Caymanian Dollar',
	bhd: 'Bahraini Dinar',
	xtz: 'Tezos',
	cny: 'Chinese Yuan Renminbi',
	bnb: 'Binance Coin',
	trx: 'TRON',
	zar: 'South African Rand',
	zmw: 'Zambian Kwacha',
	xcd: 'East Caribbean Dollar',
	gyd: 'Guyanese Dollar',
	sdg: 'Sudanese Pound',
	ars: 'Argentine Peso',
	htg: 'Haitian Gourde',
	ngn: 'Nigerian Naira',
	hot: 'Hydro Protocol',
	php: 'Philippine Peso',
	xmr: 'Monero',
	uyu: 'Uruguayan Peso',
	lrd: 'Liberian Dollar',
	aud: 'Australian Dollar',
	aed: 'Emirati Dirham',
	zwl: 'Zimbabwean Dollar',
	fkp: 'Falkland Island Pound',
	bwp: 'Botswana Pula',
	bdt: 'Bangladeshi Taka',
	stn: 'Sao Tomean Dobra',
	ugx: 'Ugandan Shilling',
	knc: 'Kyber Network Crystals',
	zil: 'Zilliqa',
	gbp: 'British Pound',
	chz: 'Chiliz',
	uni: 'Uniswap',
	scr: 'Seychellois Rupee',
	pen: 'Peruvian Sol',
	wst: 'Samoan Tala',
	twd: 'Taiwan New Dollar',
	bsv: 'Bitcoin SV',
	sos: 'Somali Shilling',
	aoa: 'Angolan Kwanza',
	xem: 'NEM',
	sbd: 'Solomon Islander Dollar',
	dzd: 'Algerian Dinar',
	kcs: 'Kucoin',
	mmk: 'Burmese Kyat',
	btt: 'BitTorrent',
	xrp: 'Ripple',
	pln: 'Polish Zloty',
	nok: 'Norwegian Krone',
	qar: 'Qatari Riyal',
	ltc: 'Litecoin',
	btn: 'Bhutanese Ngultrum',
	ada: 'Cardano',
	tjs: 'Tajikistani Somoni',
	inr: 'Indian Rupee',
	cdf: 'Congolese Franc',
	jpy: 'Japanese Yen',
	crc: 'Costa Rican Colon',
	tusd: 'True USD',
	zec: 'ZCash',
	mzn: 'Mozambican Metical',
	nexo: 'NEXO',
	one: 'Menlo One',
	mdl: 'Moldovan Leu',
	mana: 'Mana Coin Decentraland',
	gt: 'GateToken',
	bsd: 'Bahamian Dollar',
	bzd: 'Belizean Dollar',
	bch: 'Bitcoin Cash',
	hrk: 'Croatian Kuna',
	paxg: 'PAX Gold',
	mga: 'Malagasy Ariary',
	tzs: 'Tanzanian Shilling',
	usdc: 'USDC',
	nzd: 'New Zealand Dollar',
	isk: 'Icelandic Krona',
	etc: 'Ethereum Classic',
	syp: 'Syrian Pound',
	awg: 'Aruban or Dutch Guilder',
	xpf: 'CFP Franc',
	leo: 'LEOcoin',
	atom: 'Cosmos',
	cad: 'Canadian Dollar',
	qtum: 'QTUM',
	gmd: 'Gambian Dalasi',
	avax: 'Avalanche',
	xof: 'CFA Franc',
	svc: 'Salvadoran Colon',
	grt: 'The Graph',
	bbd: 'Barbadian or Bajan Dollar',
	irr: 'Iranian Rial',
	amp: 'Amp',
	rsd: 'Serbian Dinar',
	huf: 'Hungarian Forint',
	dot: 'Polkadot',
	bob: 'Bolivian Bol\u00edviano',
	rwf: 'Rwandan Franc',
	nad: 'Namibian Dollar',
	mvr: 'Maldivian Rufiyaa',
	pab: 'Panamanian Balboa',
	vnd: 'Vietnamese Dong',
	waves: 'Waves',
	tnd: 'Tunisian Dinar',
	theta: 'Theta',
	eth: 'Ethereum',
	bmd: 'Bermudian Dollar',
	cve: 'Cape Verdean Escudo',
	egp: 'Egyptian Pound',
	imp: 'Isle of Man Pound',
	rvn: 'Ravencoin',
	gip: 'Gibraltar Pound',
	lrc: 'Loopring',
	bnd: 'Bruneian Dollar'
};