import type { PageLoad } from "./$types";

let features = [
	{ img: (await import('$lib/assets/features/realtime.png')).default, title: 'Real-time Market Data', description: 'Access <b>live price updates and market movements</b> without delays, giving you the confidence to make trades at the right moment. Our platform streams data directly from trusted sources, ensuring accuracy and transparency. With real-time feeds, you’ll never miss opportunities caused by sudden shifts in currency pairs, stocks, or crypto markets. Stay ahead with <b>up-to-the-second charts, quotes, and order book depth</b> so you can analyze trends effectively. Whether you’re a beginner testing strategies or an experienced trader executing fast moves, real-time data is essential for maximizing your trading performance and minimizing risks.' },
	{ img: (await import('$lib/assets/features/demolive.png')).default, title: 'Demo & Live Accounts', description: 'Start your trading journey with the flexibility of both <b>demo and live accounts</b>. Our demo account lets you practice with virtual funds, making it the perfect risk-free environment to test strategies, learn the platform, and build confidence before entering real markets. Once you’re ready, switch to a live account and enjoy <b>authentic trading experiences</b> with real profits and losses. Seamlessly move between demo and live anytime, so you can refine skills while growing your portfolio. This feature ensures you have the <b>freedom to learn and earn</b> at your own pace.' },
	{ img: (await import('$lib/assets/features/multiassets.png')).default, title: 'Multiple Asset Classes', description: 'Expand your opportunities by trading across <b>multiple asset classes</b> including forex, stocks, commodities, and cryptocurrencies—all within one platform. Diversifying your trades helps balance risk and unlocks new profit possibilities. Whether you prefer the <b>stability of gold</b>, the <b>fast-moving world of crypto</b>, or the traditional reliability of stocks, you can easily switch between assets with a few clicks. By having everything in one place, you gain the ability to <b>build a well-rounded trading portfolio</b>, capture global market trends, and trade exactly where you see potential.' },
	{ img: (await import('$lib/assets/features/otc.png')).default, title: 'OTC Trading', description: 'Enjoy the freedom of <b>Over-the-Counter (OTC) trading</b>, where you can access deals outside traditional exchange hours and structures. OTC trading gives you more flexibility, allowing you to <b>negotiate directly with liquidity providers</b> and enjoy customized contracts that fit your trading style. This feature is especially beneficial for high-volume traders or those looking for assets not always available on public exchanges. With tighter spreads, flexible pricing, and extended trading opportunities, OTC makes it possible to trade more efficiently and profit from markets beyond standard limitations. It’s about <b>personalized trading with greater control</b>.' },
	{ img: (await import('$lib/assets/features/advanceCharting.png')).default, title: 'Advanced Charting Tools', description: 'Analyze the market with <b>professional-grade charting tools</b> designed for traders who value precision. Our platform provides a wide range of indicators, trend lines, candlestick patterns, and drawing tools to help you understand market movements in detail. From simple moving averages to complex Fibonacci retracements, you’ll have every tool needed to <b>build, test, and refine your strategy</b>. The customizable interface allows you to set up charts exactly as you like, making complex data simple to understand. With advanced charting, you can <b>spot opportunities faster</b> and trade with clarity.' },
	{ img: (await import('$lib/assets/features/oneclick.png')).default, title: 'One-Click Trading', description: 'Save precious time with <b>one-click trading</b>, designed for traders who want speed without sacrificing accuracy. Execute trades instantly without going through multiple confirmation steps, ensuring you never miss fast-moving opportunities in volatile markets. Whether you’re scalping small moves or jumping on a sudden breakout, one-click trading makes it effortless. You can also pre-set trade sizes and preferred order types, streamlining the process even further. With this feature, every second counts, and you’ll always be prepared to <b>act on market changes instantly</b>.' },
	{ img: (await import('$lib/assets/features/friendly.png')).default, title: 'User-Friendly Interface', description: 'Our platform is built around a <b>clean, intuitive design</b> that ensures smooth navigation for both beginners and professionals. From the moment you log in, you’ll find all essential tools—charts, order placement, portfolio management—organized logically for easy access. No steep learning curve, no clutter, just <b>efficient trading without distractions</b>. Whether on mobile, tablet, or desktop, the interface adapts seamlessly, letting you trade with confidence from anywhere. By focusing on usability, we make sure that <b>your trading experience is simple, fast, and enjoyable</b>.' },
	{ img: (await import('$lib/assets/features/support.png')).default, title: '24/7 Customer Support', description: 'Trading never sleeps, and neither does our <b>customer support team</b>. Available 24/7, our experts are ready to help you with everything from account setup to technical issues or trading-related questions. You can connect via live chat, email, or phone, and receive quick, reliable assistance whenever you need it. We understand that markets move fast, so <b>support without delays</b> is crucial. Our multilingual support ensures traders worldwide always feel understood and cared for. With round-the-clock assistance, you’ll never be left trading in uncertainty.' },
	{ img: (await import('$lib/assets/features/encrypted.png')).default, title: 'Encrypted Transactions', description: 'Security is at the heart of our platform, with <b>state-of-the-art encryption</b> protecting all deposits, withdrawals, and account information. Every transaction goes through multiple layers of security, ensuring your funds and personal data remain safe from threats. We employ advanced SSL protocols and bank-grade encryption, so you can trade with peace of mind knowing your money is secure. Beyond encryption, we also use <b>two-factor authentication</b> for extra account safety. With us, your financial privacy is our top priority, making trading <b>secure and worry-free</b>.' },
	{ img: (await import('$lib/assets/features/fastdeposit.png')).default, title: 'Fast Deposits & Withdrawals', description: 'Manage your money with <b>fast, hassle-free deposits and withdrawals</b>. Our platform supports multiple payment methods including bank transfers, credit cards, and e-wallets, giving you flexibility and convenience. Deposits reflect instantly so you can start trading right away, while withdrawals are processed quickly to ensure <b>you always have control of your funds</b>. Transparency is key—we never add hidden delays or unnecessary fees. With smooth transaction handling, you can focus fully on trading, knowing your capital is always <b>accessible and secure</b>.' },
];

export const load: PageLoad = async () => {
  return {features};
};


